apiVersion: v1
kind: Service
metadata:
  name: service-portal-service
spec:
  selector:
    app: service-portal
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 7070  # Match the containerPort from the Deployment
