apiVersion: v1
kind: Service
metadata:
  name: service-portal-service
spec:
  selector:
    app: service-portal
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000  # Match the containerPort from the Deployment
