apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-portal-role-binding
subjects:
- kind: ServiceAccount
  name: default # Adjust this based on the ServiceAccount you are using
  namespace: default # Adjust the namespace if needed
roleRef:
  kind: ClusterRole
  name: service-portal-role
  apiGroup: rbac.authorization.k8s.io
