apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-portal
  template:
    metadata:
      labels:
        app: service-portal
    spec:
      containers:
      - name: service-portal
        image: lioratari/kubernetes-portal:latest
        ports:
        - containerPort: 7070
