apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-all-namespaces-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"] # Add more resources as needed
  verbs: ["get", "list"]
