apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-portal-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: service-portal-role
  apiGroup: rbac.authorization.k8s.io
